source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Psychomotor Vigilance Task' do
	pod 'Alamofire', '~> 4.0'
	pod 'SwiftyJSON'
	pod 'ScrollableGraphView'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
end
